import '../styles/globals/globals.scss'
import type { Metadata } from 'next'
import { Varela_Round } from 'next/font/google'

const varelaRound = Varela_Round({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Hajae Tech Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded" rel="stylesheet" />
      </head>
      <body className={varelaRound.className}>{children}</body>
    </html>
  )
}
